version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - 8086
    networks:
      - caddy
      - influxdb_network
    labels:
      caddy: "influx.jstet.net"
      caddy.reverse_proxy: "{{upstreams 8086}}"

  telegraf:
    image: telegraf:1.19
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:rw
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - influxdb
    networks:
      - influxdb_network
    user: telegraf:1000

volumes:
  influxdb-storage:


networks:
  caddy:
    external: true
  influxdb_network:
