version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - 8086
    networks:
      - traefik_network
      - influxdb_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tistack.loadbalancer.server.port=8086"
      - "traefik.docker.network=traefik_network"
      # https
      - "traefik.http.routers.tistack.rule=Host(`influx.jstet.net`)"
      - "traefik.http.routers.tistack.tls=true"
      - "traefik.http.routers.tistack.tls.certresolver=letsencrypt"
      - "traefik.http.routers.tistack.entrypoints=websecure"
      # http (redirect to https)
      - "traefik.http.routers.tistack-http.rule=Host(`influx.jstet.net`)"
      - "traefik.http.routers.tistack-http.entrypoints=web"
      - "traefik.http.routers.tistack-http.middlewares=redirect-to-https@file"

  telegraf:
    image: telegraf:1.19
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:rw
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - influxdb
    networks:
      - influxdb_network
    user: telegraf:1000
    restart: on-failure:10

volumes:
  influxdb-storage:


networks:
  traefik_network:
    external: true
  influxdb_network:
