- name: Create dir for ti stack
    file:
      path: "/home/{{  ansible_user   }}/ti-stack"
      state: directory
      owner: "{{  ansible_user   }}"
      mode: 0775

- name: Copy docker compose to server
  template:
    src: "files/{{  app  }}-docker-compose.yml"
    dest: "/home/{{  ansible_user   }}/{{  app  }}/docker-compose.yml"

- name: deploying app
  shell: |
    cd /home/{{  ansible_user   }}/{{  app  }} && docker compose build --no-cache && docker compose up -d