version: "3.8"
services:

  postgres:
    container_name: postgres
    command: postgres -c listen_addresses='*'
    build: ./db/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    ports:
      - 5432
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always


  fastapi:
    container_name: fastapi
    build: ./api/.
    ports:
      - 8000
    networks:
      - db
      - frontend
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/main
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend/.
      args:
        - NODE_ENV=production
        - PUBLIC_API_URL=http://fastapi:8000
    ports:
      - 3000
    restart: always
    labels:
      caddy: "{{ domain }}"
      caddy.reverse_proxy: "{% raw %}{{upstreams 3000}}{% endraw %}"
    networks:
      - caddy
      - frontend

networks:
  db:
    name: db
  frontend:
    name: frontend
  caddy:
    external: true
