version: '3'
services:
  directus-cache:
    restart: always
    container_name: directus-cache
    image: redis:6-alpine
    networks:
      - directus
    ports:
      - 6379

  directus-database:
    container_name: directus-database
    ports:
      - 8055
    image: postgis/postgis:13-master
    volumes:
      - directus_database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'
    restart: always

  directus:
    restart: always
    container_name: directus
    image: directus/directus:10.7.0 
    ports:
      - 8055:8055
    networks:
      - directus
      - caddy
    depends_on:
      - directus-cache
     
    environment:
      KEY: '{{  directus_key  }}'
      SECRET: '{{  directus_secret  }}'

      DB_CLIENT: 'pg'
      DB_HOST: 'directus-database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'


      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://directus-cache:6379'
      CACHE_TTL: "60s"
      
      ADMIN_EMAIL: '{{ directus_admin_mail }}'
      ADMIN_PASSWORD: '{{  directus_admin_pw  }}'

      EMAIL_TRANSPORT: 'smtp'
      EMAIL_FROM: '{{ smtp_user }}'
      EMAIL_SMTP_HOST: '{{ smtp_host }}'
      EMAIL_SMTP_PORT: '{{ smtp_port }}'
      EMAIL_SMTP_USER: '{{ smtp_user }}'
      EMAIL_SMTP_PASSWORD: "{{ smtp_password }}"
      EMAIL_SMTP_SECURE: 'true'
      PUBLIC_URL: "https://{{  domain  }}"

      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"

      STORAGE_LOCAL_ROOT: "/directus/uploads"
    volumes:
      - directus_storage:/directus/uploads
    labels:
      caddy: "{{ domain }}"
      caddy.reverse_proxy: "{{"{{upstreams 8055}}"}}"

  

networks:
  caddy:
    external: true
  directus:

volumes:
  directus_database:
  directus_storage: 

  
