version: '3'
services:

  myrtle:
    container_name: myrtle
    image: myrtle
    build: ./
    ports:
      - 8000
    environment:
    - PRODUCTION=True
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.myrtle.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik_network"
      # https
      - "traefik.http.routers.myrtle.rule=Host(`{{  domain  }}`)"
      - "traefik.http.routers.myrtle.tls=true"
      - "traefik.http.routers.myrtle.tls.certresolver=letsencrypt"
      - "traefik.http.routers.myrtle.entrypoints=websecure"
      # http (redirect to https)
      - "traefik.http.routers.myrtle-http.rule=Host(`{{  domain  }}`)"
      - "traefik.http.routers.myrtle-http.entrypoints=web"
      - "traefik.http.routers.myrtle-http.middlewares=redirect-to-https@file"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true

