version: '3'
services:

  myrtle:
    container_name: myrtle
    image: myrtle
    build: ./
    ports:
      - 8000
    labels:
      caddy: "{{ domain }}"
      caddy.reverse_proxy: "{% raw %}{{upstreams 8000}}{% endraw %}"
    networks:
      - caddy

networks:
  caddy:
    external: true

